avoid creating files without a mode
mode MUST be provided when O_CREAT is used, so use a sane default and
report errors as the virtual equivalent creat call

fixes FTBFS for Ubuntu 13.10 because of :

  error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT in second argument needs 3 arguments